2022-08-03 02:15:27,504 ERROR Exception on / [GET] [in /home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/smr/Desktop/new/flask-grinberg/myapp/routes.py", line 42, in index
    return render_template("index.html", title="Home", posts=myposts)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/smr/Desktop/new/flask-grinberg/myapp/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/smr/Desktop/new/flask-grinberg/myapp/templates/base.html", line 40, in top-level template code
    {% block content %}
  File "/home/smr/Desktop/new/flask-grinberg/myapp/templates/index.html", line 8, in block 'content'
    <p>{{ form.body.label }}</p>
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-08-03 02:15:48,178 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:16:22,902 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:21:32,606 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:22:58,859 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:25:13,626 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:28:10,609 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:32:33,134 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
2022-08-03 02:32:37,224 ERROR Exception on / [GET] [in /home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/smr/Desktop/new/flask-grinberg/myapp/routes.py", line 42, in index
    return render_template("index.html", title="Home", posts=myposts,form=post_form)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/smr/Desktop/new/flask-grinberg/myapp/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/smr/Desktop/new/flask-grinberg/myapp/templates/base.html", line 40, in top-level template code
    {% block content %}
  File "/home/smr/Desktop/new/flask-grinberg/myapp/templates/index.html", line 7, in block 'content'
    {{ csrf_token() }}
  File "/home/smr/Desktop/new/flask-grinberg/venv/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'csrf_token' is undefined
2022-08-03 02:33:32,023 INFO Microblog startup [in /home/smr/Desktop/new/flask-grinberg/myapp/logger.py:61]
